### ISSUE TITLE
installation error

### ISSUE THREAD

**Issue by blsfoxfox** [isovic/racon#12] opened 2017-01-11 15:54 UTC
Hi,

I am trying to install Racon, but get the following error:

Receiving objects: 100% (390/390), 219.53 KiB, done.
Resolving deltas: 100% (270/270), done.
fatal: reference is not a tree: c649058e49e1c2d2f9919964219582a447efe6a1
Unable to checkout 'c649058e49e1c2d2f9919964219582a447efe6a1' in submodule path 'codebase/spoa'
Makefile:49: recipe for target 'modules' failed
make: *** [modules] Error 1

I have no idea how to solve this, so please help.
Bob

**Comment by rvaser** [comment] 2017-01-11 16:39
Hello Bob,

I think the issue is fixed now, please try a fresh install.

Best regards,
Robert

**Closed** 2017-01-16 08:32 UTC
